name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: server_config

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            git clone https://github.com/Y0rFa1se/API-SERVER.git
            cd API-SERVER
            echo "${{ secrets.DOTENV }}" > .env

            if [ -n "$(docker ps -q -f "name=api_server-8001")" ]; then
              docker build -t api_server-8002 .
              echo "8001 exist"
              docker run -d --name api_server-8002 -v storage:/storage -p 8002:8001 api_server-8002

              while ! curl -s http://192.168.0.18:8002; do
                sleep 5
              done

              docker stop api_server-8001 || true
              docker rm api_server-8001 || true
              docker rmi api_server-8001 || true

            elif [ -n "$(docker ps -q -f "name=api_server-8002")" ]; then
              docker build -t api_server-8001 .
              echo "8002 exist"
              docker run -d --name api_server-8001 -v storage:/storage -p 8001:8001 api_server-8001

              while ! curl -s http://192.168.0.18:8001; do
                sleep 5
              done

              docker stop api_server-8002 || true
              docker rm api_server-8002 || true
              docker rmi api_server-8002 || true

            else
              docker build -t api_server-8001 .
              echo "doesn't exist"
              docker run -d --name api_server-8001 -v storage:/storage -p 8001:8001 api_server-8001

            fi

            cd ..
            rm -rf API-SERVER
